---
# Title of the website. Required.
title: "AwesomeDocs"

# Description of the website. Required.
description: "AwesomeDocs is a React based open-source documentation site generator. Build beautiful, blazing fast documentation sites for your projects with just markdown."

# URL to the logo of your site. Optional.
logo: "https://github.com/AwesomeDocs.png"

# Link to the git repository. Optional.
repository: "https://github.com/AwesomeDocs"

# Link to the twitter account. Optional.
twitter: "https://twitter.com/k3rn31p4nic"

# Link to the main website. Optional.
website: "https://awesomedocs.traction.one"

# Copyright notice that would be placed in the footer. Optional.
copyright: "Copyright 2020 - Sankarsan Kampa"

# List of links for the header. Optional.
links:
- name: "Author"
  link: "https://traction.one"
- name: "Author's GitHub"
  link: "https://github.com/k3rn31p4nic"

# List of items for the navigating the documentation.
navigation:
- section: "Intro"
  links:
  - name: "Home"
    link: "/"
- section: "Example"
  links:
  - name: "Internal Link"
    link: "/404"
  - name: "External Link"
    link: "https://traction.one"
